apiVersion: v1
kind: Service
metadata:
  name: my-todo-app
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
